networks:
  libooktrac-network:

services:  
  libooktrac-backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      .env
    container_name: libooktrac-backend
    volumes:
      - .:/workspace
    working_dir: /workspace
    networks:
      - libooktrac-network
    depends_on:
      libooktrac-db:
        condition: service_healthy

  libooktrac-db:
      image: postgres:latest
      env_file:
        - .env
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      container_name: libooktrac-database
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d libooktrac"]
        interval: 30s
        timeout: 30s
        retries: 5
      networks:
        - libooktrac-network

volumes:
    postgres_data: