services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: libooktrac:latest
    container_name: libooktrac-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/libooktrac
    networks:
      - libooktrac-network

  mongodb:
    image: mongo:latest
    container_name: libooktrac-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=libooktrac
    networks:
      - libooktrac-network

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  libooktrac-network:
    driver: bridge