name: LibookTrac CI-CD

on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"

jobs:
  tests:
    name: Run Test
    uses: ./.github/workflows/test-lint.yaml
    secrets: inherit