name: LibookTrac CI-CD

on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"

jobs:
  tests:
    name: Run Test
    uses: ./.github/workflows/test-lint.yaml
    secrets: inherit

  docker:
    name: Build and Push Docker Image
    uses: ./.github/workflows/push-image.yaml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    needs: tests
    if: github.event_name == 'push' 
    # && github.ref == 'refs/heads/main'
    # && github.event.pull_request.merged == true