name: LibookTrac CI-CD

on:
  push:
    branches:
      - "main"
      - "feature/**"
    paths-ignore:
      - 'docs/**'
      - 'LICENSE'
      - 'Makefile'
      - 'README.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - 'docs/**'
      - 'LICENSE'
      - 'Makefile'
      - 'README.md'

jobs:
  tests:
    name: Run Test
    uses: ./.github/workflows/test-lint.yaml
    secrets: inherit

  docker:
    name: Build and Push Docker Image
    uses: ./.github/workflows/push-image.yaml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    needs: tests
    if: github.ref == 'refs/heads/main'