name: Run Tests

on:
  workflow_call:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test with pytest
        run: |
          if ls tests/*.py 1> /dev/null 2>&1; then
            pytest -v tests/
          else
            echo "No tests found, skipping..."
          fi